# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Edi Hasaj
author:      Edi Hasaj
email:       ''
description: 'Software, AI and Thinking.'
#baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://edihasaj.com' # The base hostname & protocol for your site
twitter:     'https://x.com/hasajedi'
github:      'https://github.com/edihasaj'
instagram:   'https://www.instagram.com/edihasaj/'
facebook:    'https://www.facebook.com/hasajedi'
linkedin:    'https://www.linkedin.com/in/edihasaj/'

markdown:  kramdown
paginate:  30

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-mentions
  - jekyll-feed
  - jekyll-redirect-from

include:
  - _pages
  - posts

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
permalink: /:categories/:title

feed:
  path: atom.xml

#collections_dir: obsidian

collections:
  posts:
    output: true
    permalink: /:title

  guide:
    output: true
    permalink: /:title

# Pages path
defaults:
  - scope:
      path: ''
    values:
      layout: post

  - scope:
      path: 'obsidian/posts'
    values:
      permalink: posts/:title

  - scope:
      path: 'obsidian/guide'
    values:
      permalink: guide/:title

  - scope:
      path: 'obsidian*'
    values:
      permalink: /:basename

  - scope:
      path: 'posts'
    values:
      layout: post

  - scope:
      path: 'guide'
    values:
      layout: post

  - scope:
      path: '_pages'
    values:
      layout: page
      permalink: /:basename
